ntl_test_x:ntl_test.cpp
	g++ -g -O2 -I/usr/local/include ntl_test.cpp -o ntl_test_x -L/usr/share/lib -lntl -lgmp -lm

field_test_x:field_test.cpp
	g++ -g -O2 -I/usr/local/include field_test.cpp -o field_test_x -L/usr/share/lib -lntl -lgmp -lm

clean:
	rm *_x
